version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: moa
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  springboot:
    image: backend
    build: ./backend
    container_name: moa
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:6.2
    container_name: redis
    environment:
      TZ: Asia/Seoul
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no"]
    restart: always

env_file:
  - /home/ubuntu/.env
