services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    env_file:
      - /var/jenkins_home/workspace/SpringServer/.env
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  # root 비밀번호 설정
      MYSQL_DATABASE: moa                 # 기본 데이터베이스 설정
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql


  springboot:
    image: backend
    build: ./backend
    container_name: moa
    env_file:
      - /var/jenkins_home/workspace/SpringServer/.env  # Jenkins에서 사용하는 .env 파일 경로
    volumes:
      - /var/jenkins_home/workspace/SpringServer/.env:/app/.env  # Spring Boot가 접근할 수 있도록 마운트
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis

  redis:
    image: redis:6.2
    container_name: redis
    environment:
      TZ: Asia/Seoul
    ports:
      - "6379:6379"
    command: ["redis-server", "--bind", "0.0.0.0", "--protected-mode", "no"]
    restart: always
